name: integration testing

on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example
    steps:
    - name: pwd
      run: pwd


