name: integration testing

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.1,name=iPhone 8']
      fail-fast: false
    defaults:
      run:
        working-directory: example
    # steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: start Simulator
      run: open -a Simulator
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter drive --profile

